apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xankong-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - xankong.app
    secretName: xankong-tls
  rules:
  - host: xankong.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: xankong-service
            port:
              number: 80
